name: 'Build dll files'

on:
  workflow_dispatch:

jobs:

  build:
    name: Build

    runs-on: windows-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Run nmake
      run: nmake /f Makefile.vc CFG=release-dynamic RTLIBCFG=dynamic OBJDIR=output
