name: 'Build stuff files'

on:
  push:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Name of the branch to build'
        required: true
        default: 'main'

jobs:

  build-windows:
    name: Build Windows
    runs-on: windows-latest

    strategy:
      matrix:
        arch:
          - x86
          - x64

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        ref: '${{ github.event.inputs.branchName }}'

    - name: Enable Developer Command Prompt (${{ matrix.arch }})
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Run nmake
      run: nmake /f Makefile.vc CFG=release-dynamic RTLIBCFG=dynamic OBJDIR=output

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libwebp-dll-${{ matrix.arch }}
        path: ./output/**/*.dll
        if-no-files-found: error

  buildl-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
      with:
        ref: '${{ github.event.inputs.branchName }}'

    - name: Run nmake
      run: |
        ./configure
        make
        make install
